- source: ./                     # 源仓库根目录
  dest: SWEEP-office/COLID-OS--Community-Edition
  target_path: NS/               # 目标文件夹
  exclude:
    - .github/                   # 不同步 .github 目录（包含 workflows）
    - .git/                      # 保险，忽略版本控制目录
  delete_orphaned: true          # 目标文件夹与源仓库完全一致
